SELECT * FROM TEACHERS
WHERE TEACHERS.TFAM IN('Козанко','Казанко','Козанков') 


SELECT COUNT(STUDENTS.SNUM) AS stud_col, STUDENTS.STIP FROM STUDENTS
GROUP BY (STUDENTS.STIP)
ORDER BY (stud_col) DESC

SELECT * FROM STUDENTS
WHERE STUDENTS.SNUM IN(
  SELECT USP.SNUM 
  FROM USP
  WHERE "USP"."UPDATE" = '1999-06-10'
)

SELECT STUDENTS.SFAM, STUDENTS.SNUM FROM STUDENTS 
WHERE STUDENTS.SNUM IN(
  SELECT STUDENTS.SNUM FROM USP
  INNER JOIN STUDENTS ON STUDENTS.SNUM = USP.SNUM
  GROUP BY STUDENTS.SNUM
  HAVING COUNT(*) > 1
)

SELECT USP."UPDATE", AVG(CONVERT(float, USP.OCENKA)) AS avg_ocenka
FROM USP
GROUP BY USP."UPDATE"
HAVING AVG(CONVERT(float, USP.OCENKA)) = (
  SELECT MIN(CONVERT(float, USP.OCENKA))
  FROM USP
)

SELECT COUNT(DISTINCT USP.SNUM) AS Количество_студентов
FROM USP
WHERE USP.PNUM = 2003 AND USP.OCENKA > (
  SELECT AVG(USP.OCENKA)
  FROM USP
  WHERE USP.PNUM = 2003
);

SELECT *
FROM PREDMET
WHERE PREDMET.PNUM = (
  SELECT PREDMET.PNUM - 1
  FROM PREDMET
  WHERE PREDMET.PNAME = 'Философия'
);

SELECT *
FROM PREDMET
WHERE PREDMET.PNAME LIKE '%\_%' ESCAPE '\'